"""New migration for additional changes

Revision ID: b697e40aa02b
Revises: c1dee4b2a666
Create Date: 2025-01-24 13:44:31.115859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b697e40aa02b'
down_revision: Union[str, None] = 'c1dee4b2a666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
